### ISSUE TITLE
Create yaml files to have an easy machine actionable checklists description

### ISSUE THREAD

**Issue by bedroesb** [ELIXIR-Belgium/ENA-metadata-templates#12]
Every checklist will have next to their xlsx and tsv tables a yaml file with following attributes:
name, cardinality, description, cv (list), units 

THis yaml will be easisly digestable for other services

Example:

```yml
run:
 - name: Attribute name
   cardinality: optional
   description: This is a description of the attribute
   cv: 
    - test
    - test
   units: m/s
 - name: Attribute name
   cardinality: optional
   description: This is a description of the attribute
   cv: 
    - test
    - test
   units: m/s
study:
 - name: Attribute name
   cardinality: optional
   description: This is a description of the attribute
   cv: 
    - test
    - test
   units: m/s
 - name: Attribute name
   cardinality: optional
   description: This is a description of the attribute
   cv: 
    - test
    - test
   units: m/s


```
